- name: nginx install and run
  hosts: web
  become: yes
  tasks:
   - name: install nginx
     ansible.builtin.package:
       name: nginx
       state: present


   - name: install nginx
     ansible.builtin.service:
       name: nginx
       state: started
       enabled: yes
