- name: variables to print
  hosts: web
  vars:
    course: devops with aws
    trainer: sivakumar reddy
  tasks: 
  - name: print the information
    ansible.builtin.debug:
     msg: "hi iam learning {{course}},trainer: {{trainer}}"